# Generated by Django 4.2.8 on 2023-12-09 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropout', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='display_name',
            new_name='people',
        ),
    ]
