# Generated by Django 4.2.8 on 2023-12-09 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropout', '0002_rename_display_name_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='place_of_birth',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
